#!/usr/bin/env escript
%% -*- erlang -*-
-module(copy_docs).

main([DestDir]) ->
	Files = filelib:fold_files( "../lib", ".*\\.md$", true, fun(File, Acc) -> [File|Acc] end, []),
	lists:foreach(fun(SourcePath) ->
		CopyPath = filename:join(DestDir, filename:basename(SourcePath)),
		file:copy(SourcePath, CopyPath)
	end, Files).