// @ts-check

export const keys = {
  autocomplete: "autoComplete",
  autofocus:    "autoFocus",
  class:        "className",
  className:    "className",
  enctype:      "encType",
  formaction:   "formAction",
  frameborder:  "frameBorder",
  maxlength:    "maxLength",
  minlength:    "minLength",
  onblur:       "onBlur",
  onchange:     "onChange",
  onclick:      "onClick",
  onfocus:      "onFocus",
  oninput:      "onInput",
  onkeydown:    "onKeyDown",
  onkeyup:      "onKeyUp",
  onmousedown:  "onMouseDown",
  onmouseout:   "onMouseOut",
  onmouseover:  "onMouseOver",
  onmouseup:    "onMouseUp",
  onscroll:     "onScroll",
  onsubmit:     "onSubmit",
  ontouchend:   "onTouchEnd",
  ontouchmove:  "onTouchMove",
  ontouchstart: "onTouchStart",
  readonly:     "readOnly",
  tabindex:     "tabIndex",
};
